# Generated by Django 4.0.6 on 2022-07-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0002_alter_qnaquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qna.qnaquestion', verbose_name='질문'),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='답변자'),
        ),
    ]
