# Generated by Django 4.0.6 on 2022-07-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_alter_qnaanswer_question_alter_qnaanswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaanswer',
            name='is_selected',
            field=models.BooleanField(null=True, verbose_name='채택여부'),
        ),
    ]
