# Generated by Django 4.0.6 on 2022-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_alter_qnaanswer_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='qnaquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지'),
        ),
    ]
