# Generated by Django 4.0.6 on 2022-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_qnaanswer_image_qnaquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaquestion',
            name='hashtag',
            field=models.TextField(default='#python', verbose_name='해시태그'),
        ),
    ]
