# Generated by Django 4.0.6 on 2022-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_qnaquestion_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaquestion',
            name='image',
            field=models.ImageField(blank=True, default='https://s3.ap-northeast-2.amazonaws.com/gomunity.shop/media/externalFile.jpg', upload_to='', verbose_name='이미지'),
        ),
    ]
