# Generated by Django 4.0.6 on 2022-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_alter_qnaquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지'),
        ),
    ]
