# Generated by Django 4.0.6 on 2022-08-12 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='썸네일 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtag', models.TextField(verbose_name='해시태그')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변')),
                ('image', models.ImageField(upload_to='uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archive', verbose_name='자료')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archiveanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archiveanswer',
            name='like',
            field=models.ManyToManyField(related_name='archive_answerlike', through='archive.ArchiveAnswerLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiveanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='답변자'),
        ),
        migrations.AddField(
            model_name='archive',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archivecategory', verbose_name='자료게시판 카테고리'),
        ),
        migrations.AddField(
            model_name='archive',
            name='like',
            field=models.ManyToManyField(related_name='archive_like', through='archive.ArchiveLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='자료게시판 작성자'),
        ),
    ]
