# Generated by Django 4.0.6 on 2022-08-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='썸네일 이미지'),
        ),
        migrations.AlterField(
            model_name='archiveanswer',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
